In [1]:
def dfs(graph, start, visited=None, stack=None):
    if visited is None:
        visited = set()
    if stack is None:
        stack = []
    
    print("当前访问节点:", start)
    visited.add(start)
    stack.append(start)
    print("节点", start, "入栈")
    for neighbor in graph[start]:
        if neighbor not in visited:
            dfs(graph, neighbor, visited, stack)
    
    print("节点", stack.pop(), "出栈")

# 用邻接表表示图
graph = {
    7: [4, 3],
    4: [2, 9],
    3: [],
    2: [6],
    9: [],
    6: []
}

# 从节点7开始深度优先搜索
print("深度优先搜索结果:")
dfs(graph, 7)


深度优先搜索结果:
当前访问节点: 7
节点 7 入栈
当前访问节点: 4
节点 4 入栈
当前访问节点: 2
节点 2 入栈
当前访问节点: 6
节点 6 入栈
节点 6 出栈
节点 2 出栈
当前访问节点: 9
节点 9 入栈
节点 9 出栈
节点 4 出栈
当前访问节点: 3
节点 3 入栈
节点 3 出栈
节点 7 出栈


In [2]:
import numpy as np

# 给定的数组
array = [2, 6, 8, 5, 3, 7, 1, 4]
n = len(array)

# 初始化邻接矩阵为全0
adj_matrix = np.zeros((n, n), dtype=int)

# 将数组中相邻元素的索引之间的连接关系表示为1
for i in range(n - 1):
    adj_matrix[i][i + 1] = 1
    adj_matrix[i + 1][i] = 1

print("邻接矩阵：")
print(adj_matrix)

邻接矩阵：
[[0 1 0 0 0 0 0 0]
 [1 0 1 0 0 0 0 0]
 [0 1 0 1 0 0 0 0]
 [0 0 1 0 1 0 0 0]
 [0 0 0 1 0 1 0 0]
 [0 0 0 0 1 0 1 0]
 [0 0 0 0 0 1 0 1]
 [0 0 0 0 0 0 1 0]]


In [5]:
def build_adj_matrix(array):
    n = len(array)
    adj_matrix = [[0] * n for _ in range(n)]

    for i in range(n):
        left_child = 2 * i + 1
        right_child = 2 * i + 2

        if left_child < n:
            adj_matrix[i][left_child] = 1
            adj_matrix[left_child][i] = 1

        if right_child < n:
            adj_matrix[i][right_child] = 1
            adj_matrix[right_child][i] = 1

    return adj_matrix

# 给定的数组
array = [2, 6, 8, 5, 3, 7, 1, 4]

# 构建邻接矩阵
adj_matrix = build_adj_matrix(array)

# 输出邻接矩阵
print("邻接矩阵：")
for row in adj_matrix:
    print(row)


邻接矩阵：
[0, 1, 1, 0, 0, 0, 0, 0]
[1, 0, 0, 1, 1, 0, 0, 0]
[1, 0, 0, 0, 0, 1, 1, 0]
[0, 1, 0, 0, 0, 0, 0, 1]
[0, 1, 0, 0, 0, 0, 0, 0]
[0, 0, 1, 0, 0, 0, 0, 0]
[0, 0, 1, 0, 0, 0, 0, 0]
[0, 0, 0, 1, 0, 0, 0, 0]


In [6]:
def build_adjacency_list(arr):
    adjacency_list = {}
    
    for i, node_value in enumerate(arr):
        neighbors = []
        
        # 计算相邻节点的索引
        left_index = i * 2 + 1
        right_index = i * 2 + 2
        
        # 添加相邻节点到列表
        if left_index < len(arr):
            neighbors.append(arr[left_index])
        if right_index < len(arr):
            neighbors.append(arr[right_index])
        
        # 将节点值及其相邻节点列表添加到邻接表中
        adjacency_list[node_value] = neighbors if neighbors else '[ ]'
    
    return adjacency_list

# 数组
arr = [2, 6, 8, 5, 3, 7, 1, 4]

# 构建邻接表
adj_list = build_adjacency_list(arr)

# 打印邻接表
for node_value, neighbors in adj_list.items():
    print(f"{node_value}: {neighbors}")


2: [6, 8]
6: [5, 3]
8: [7, 1]
5: [4]
3: [ ]
7: [ ]
1: [ ]
4: [ ]


In [ ]:
def dfs(层数,其他参数):
    if (出局判断):  #到达最底层或满足退出条件
        更新答案  #答案一般用全局变量表示
        return  #返回到上一层
    
    剪枝  #在进一步dfs之前进行剪枝

    for(枚举下一层可能的情况):  #对每一个情况继续dfs
        if(used[i] == 0):  #如果状态i没有被占用，就可以进入下一层
            used[i] == 1  #标记状态i，表示已经被用过，在更底层不能被使用
            dfs(层数+1,其他参数)  #下一层
            used[i] = 0  #恢复状态，回溯时，不影响上一层对这个状态的使用

    return  #返回上一层

In [3]:
def build_tree(nodes):
    # 创建一个字典来表示树的结构
    tree = {}
    # 遍历每个节点，构建树的结构
    for i, node in enumerate(nodes):
        # 根节点没有父节点
        if i == 0:
            continue
        # 获取当前节点的父节点索引
        parent = (i - 1) // 2
        # 将当前节点添加到父节点的子节点列表中
        tree.setdefault(nodes[parent], []).append(node)
    return tree

def bfs_tree(tree):
    # 使用队列来进行广度优先搜索
    queue = [list(tree.keys())[0]]  # 根节点的索引为0
    # 遍历队列，逐层打印树节点
    while queue:
        node = queue.pop(0)
        print(node, end=' ')
        # 将当前节点的子节点添加到队列中
        children = tree.get(node, [])
        queue.extend(children)

# 给定的数组表示树的节点
nodes = (7, 4, 3, 2, 9, 6)
# 构建树的结构
tree = build_tree(nodes)
# 以根节点开始进行BFS遍历
bfs_tree(tree)


7 4 3 2 9 6 

In [10]:
import random
import time

def bfs(array):
    result = []
    queue = [array[0]]  # 用列表模拟队列，并将根节点放入队列中
    index = 1  # 当前遍历到的数组索引

    while queue:
        node = queue.pop(0)  # 出队
        result.append(node)  # 将出队的节点添加到结果中

        left_child_index = 2 * index  # 左孩子节点的索引
        right_child_index = 2 * index + 1  # 右孩子节点的索引

        if left_child_index <= len(array):  # 检查左孩子节点是否在数组范围内
            queue.append(array[left_child_index - 1])  # 将左孩子节点入队

        if right_child_index <= len(array):  # 检查右孩子节点是否在数组范围内
            queue.append(array[right_child_index - 1])  # 将右孩子节点入队

        index += 1  # 更新当前遍历到的数组索引

    return result

# 生成100个随机数并转化为数组
random_numbers = [random.randint(0, 1000) for _ in range(999)]

# 测量函数运行时间
start_time = time.time()
result = bfs(random_numbers)
end_time = time.time()

# 计算运行时间
running_time = end_time - start_time
print("BFS 运行时间: {:.6f} 秒".format(running_time))

BFS 运行时间: 0.001008 秒


In [11]:
import queue
import time
import random

def bfs(array):
    result = []
    q = queue.Queue()
    q.put(array[0])  # 将根节点放入队列中
    index = 1  # 当前遍历到的数组索引

    while not q.empty():
        node = q.get()  # 出队
        result.append(node)  # 将出队的节点添加到结果中

        left_child_index = 2 * index  # 左孩子节点的索引
        right_child_index = 2 * index + 1  # 右孩子节点的索引

        if left_child_index <= len(array):  # 检查左孩子节点是否在数组范围内
            q.put(array[left_child_index - 1])  # 将左孩子节点入队

        if right_child_index <= len(array):  # 检查右孩子节点是否在数组范围内
            q.put(array[right_child_index - 1])  # 将右孩子节点入队

        index += 1  # 更新当前遍历到的数组索引

    return result

# 生成100个随机数并转化为数组
random_numbers = [random.randint(0, 1000) for _ in range(999)]

# 测量函数运行时间
start_time = time.time()
result = bfs(random_numbers)
end_time = time.time()

# 计算运行时间
running_time = end_time - start_time
print("BFS 运行时间: {:.6f} 秒".format(running_time))
print("BFS 遍历结果:", result)


BFS 运行时间: 0.002000 秒
BFS 遍历结果: [371, 419, 901, 112, 608, 45, 592, 373, 539, 801, 880, 210, 741, 604, 824, 307, 248, 272, 159, 968, 376, 281, 899, 812, 96, 700, 896, 553, 522, 539, 196, 888, 187, 273, 165, 727, 469, 224, 454, 217, 462, 611, 278, 972, 783, 88, 518, 350, 656, 891, 935, 496, 606, 894, 511, 400, 879, 822, 82, 845, 498, 650, 563, 79, 962, 517, 722, 520, 280, 750, 438, 549, 85, 686, 179, 805, 542, 461, 754, 473, 165, 334, 496, 28, 499, 610, 108, 30, 868, 883, 218, 30, 737, 943, 342, 790, 786, 913, 418, 182, 577, 445, 643, 660, 960, 887, 482, 871, 54, 115, 605, 842, 599, 555, 542, 96, 694, 542, 742, 29, 129, 899, 793, 930, 999, 480, 883, 367, 955, 934, 867, 649, 936, 59, 887, 5, 53, 238, 725, 800, 372, 504, 392, 181, 620, 223, 569, 86, 391, 775, 629, 541, 216, 474, 20, 162, 476, 642, 36, 376, 78, 648, 191, 764, 686, 995, 537, 902, 776, 755, 530, 418, 918, 470, 768, 446, 530, 992, 272, 642, 523, 381, 576, 8, 150, 116, 200, 170, 314, 12, 459, 254, 588, 94, 874, 433, 1000, 144, 2

In [13]:
import collections
import time
import random

def bfs(array):
    result = []
    q = collections.deque()
    q.append(array[0])  # 将根节点放入队列中
    index = 1  # 当前遍历到的数组索引

    while q:
        node = q.popleft()  # 出队
        result.append(node)  # 将出队的节点添加到结果中

        left_child_index = 2 * index  # 左孩子节点的索引
        right_child_index = 2 * index + 1  # 右孩子节点的索引

        if left_child_index <= len(array):  # 检查左孩子节点是否在数组范围内
            q.append(array[left_child_index - 1])  # 将左孩子节点入队

        if right_child_index <= len(array):  # 检查右孩子节点是否在数组范围内
            q.append(array[right_child_index - 1])  # 将右孩子节点入队

        index += 1  # 更新当前遍历到的数组索引

    return result

# 生成100个随机数并转化为数组
random_numbers = [random.randint(0, 1000) for _ in range(999)]

# 测量函数运行时间
start_time = time.time()
result = bfs(random_numbers)
end_time = time.time()

# 计算运行时间
running_time = end_time - start_time
print("BFS 运行时间: {:.6f} 秒".format(running_time))
print("BFS 遍历结果:", result)


BFS 运行时间: 0.000000 秒
BFS 遍历结果: [316, 658, 508, 600, 862, 507, 586, 192, 75, 58, 318, 848, 901, 184, 83, 299, 526, 66, 783, 944, 260, 82, 322, 429, 960, 808, 141, 940, 479, 33, 824, 266, 736, 863, 830, 155, 719, 538, 981, 811, 400, 330, 285, 894, 192, 551, 922, 48, 352, 424, 402, 227, 388, 770, 873, 238, 714, 415, 651, 595, 818, 196, 141, 585, 202, 189, 382, 103, 792, 581, 362, 699, 623, 511, 948, 93, 973, 179, 78, 259, 321, 637, 140, 875, 671, 409, 146, 523, 993, 729, 454, 277, 315, 487, 876, 82, 850, 86, 587, 828, 767, 936, 756, 433, 306, 364, 90, 507, 673, 21, 17, 352, 515, 446, 133, 92, 575, 957, 88, 468, 687, 85, 607, 419, 295, 627, 353, 237, 599, 653, 134, 832, 912, 828, 205, 962, 443, 777, 960, 870, 946, 662, 605, 150, 131, 960, 269, 306, 767, 390, 466, 239, 336, 518, 674, 162, 424, 386, 845, 841, 867, 220, 490, 368, 874, 409, 414, 470, 846, 204, 141, 789, 551, 999, 739, 78, 837, 622, 124, 602, 187, 180, 435, 33, 831, 518, 400, 43, 487, 834, 422, 202, 298, 198, 24, 733, 575, 487,

In [16]:
def bfs_with_all_paths(graph, start, end):
    queue = [(start, [start])]  # 初始时将起点及其路径放入队列中
    all_paths = []  # 用于存储所有找到的路径

    while queue:
        node, path = queue.pop(0)  # 出队
        if node == end:
            all_paths.append(path)  # 找到目标节点，将路径添加到结果列表中
        for neighbor in graph[node]:
            if neighbor not in path:  # 避免回路
                new_path = path + [neighbor]  # 生成新路径
                queue.append((neighbor, new_path))  # 将邻居节点及其路径加入队列
                # 输出搜索过程中的路径
                print("当前路径:", new_path)
    
    return all_paths

# 示例图结构
graph = {
    'A': ['B', 'C'],
    'B': ['D', 'E'],
    'C': ['F'],
    'D': [],
    'E': ['F'],
    'F': []
}

start_node = 'A'
end_node = 'F'

all_paths = bfs_with_all_paths(graph, start_node, end_node)
print("所有路径：", all_paths)


当前路径: ['A', 'B']
当前路径: ['A', 'C']
当前路径: ['A', 'B', 'D']
当前路径: ['A', 'B', 'E']
当前路径: ['A', 'C', 'F']
当前路径: ['A', 'B', 'E', 'F']
所有路径： [['A', 'C', 'F'], ['A', 'B', 'E', 'F']]


In [17]:
def bfs_with_backtracking(graph, start, end):
    queue = [(start, [start])]  # 初始时将起点及其路径放入队列中

    while queue:
        node, path = queue.pop(0)  # 出队
        if node == end:
            return path  # 找到目标节点，直接返回路径
        for neighbor in graph[node]:
            if neighbor not in path:  # 避免回路
                new_path = path + [neighbor]  # 生成新路径
                queue.append((neighbor, new_path))  # 将邻居节点及其路径加入队列
                # 输出搜索过程中的路径
                print("当前路径:", new_path)

    return None  # 如果没找到路径，则返回 None

# 示例图结构
graph = {
    'A': ['B', 'C'],
    'B': ['D', 'E'],
    'C': ['F'],
    'D': [],
    'E': ['F'],
    'F': []
}

start_node = 'A'
end_node = 'F'

path = bfs_with_backtracking(graph, start_node, end_node)
print("回溯路径：", path)


当前路径: ['A', 'B']
当前路径: ['A', 'C']
当前路径: ['A', 'B', 'D']
当前路径: ['A', 'B', 'E']
当前路径: ['A', 'C', 'F']
当前路径: ['A', 'B', 'E', 'F']
回溯路径： ['A', 'C', 'F']


In [6]:
from collections import deque

def bfs(maze, start, end):
    # 定义方向：上、下、左、右
    directions = [(-1, 0), (1, 0), (0, -1), (0, 1)]
    rows, cols = len(maze), len(maze[0])
    
    # 记录访问过的位置
    visited = set()
    visited.add(start)
    
    # 使用队列来进行广度优先搜索
    queue = deque([(start, 0)])  # 元素为当前位置和步数
    
    while queue:
        (x, y), steps = queue.popleft()
        print("当前位置:", (x, y), "步数:", steps)
        
        if (x, y) == end:
            print("找到出口，步数:", steps)
            return
        
        # 探索当前位置的相邻位置
        for dx, dy in directions:
            nx, ny = x + dx, y + dy
            if 0 <= nx < rows and 0 <= ny < cols and maze[nx][ny] == '0' and (nx, ny) not in visited:
                visited.add((nx, ny))
                queue.append(((nx, ny), steps + 1))
    
    print("搜索结束，没有找到出口。")

maze = [
    "0011111111",
    "1000100011",
    "1110001111",
    "1000100011",
    "1111111000"
]

start = (0, 0)  # 起点坐标
end = (4, 9)    # 终点坐标

bfs(maze, start, end)


当前位置: (0, 0) 步数: 0
当前位置: (0, 1) 步数: 1
当前位置: (1, 1) 步数: 2
当前位置: (1, 2) 步数: 3
当前位置: (1, 3) 步数: 4
当前位置: (2, 3) 步数: 5
当前位置: (3, 3) 步数: 6
当前位置: (2, 4) 步数: 6
当前位置: (3, 2) 步数: 7
当前位置: (2, 5) 步数: 7
当前位置: (3, 1) 步数: 8
当前位置: (1, 5) 步数: 8
当前位置: (3, 5) 步数: 8
当前位置: (1, 6) 步数: 9
当前位置: (3, 6) 步数: 9
当前位置: (1, 7) 步数: 10
当前位置: (3, 7) 步数: 10
当前位置: (4, 7) 步数: 11
当前位置: (4, 8) 步数: 12
当前位置: (4, 9) 步数: 13
找到出口，步数: 13
