In [2]:
import numpy as np #导入numpy  
  
lst = np.array([2,1,3]) #构建数组  

#打印数组内每个元素的内存地址  
for i in range(len(lst)):  
    print(id(lst[i]))

2452213855824
2451570734800
2451570734800


In [3]:
import numpy as np #导入numpy 

a_lst = np.array(["aaa","bbb","ccc"])
print(a_lst)

b_lst = np.array([[1,2],[2,3],[3,4]])
print(b_lst)

c_lst = np.array([2,1,3])
print(c_lst)

d_lst = np.array([2,"aaa",[1,2]])
print(d_lst)

['aaa' 'bbb' 'ccc']
[[1 2]
 [2 3]
 [3 4]]
[2 1 3]


ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

In [ ]:
import numpy as np #导入numpy

a = [2,1,3]
a_ary = np.array(a)

print(type(a))
print(type(a_ary))

<class 'list'>
<class 'numpy.ndarray'>


In [ ]:
import numpy as np #导入numpy

a_ary = np.array([2,1,3])
print(a_ary[0])

a_ary[0] = 5
print(a_ary)

2
[5 1 3]


In [ ]:
import numpy as np #导入numpy 

a_lst = [1,2,3]
b_lst = [2,3,4]

a_ary = np.array(a_lst)
b_ary = np.array(b_lst)

print(a_lst + b_lst)
print(a_ary + b_ary)

[1, 2, 3, 2, 3, 4]
[3 5 7]


In [ ]:
class Node:  
    def __init__(self, data=None):  
        self.data = data  
        self.next = None 
  
class LinkedList:  
    def __init__(self):  
        self.head = None 
  
    #创建链表  
    def createList(self, n):  
        for i in range(n):  
            node = Node(int(input(f"Enter data for node {i + 1}: ")))  
            if self.head is None:  
                self.head = node  
            else:  
                current = self.head  
                while current.next is not None:  
                    current = current.next  
                current.next = node  
  
    #输出链表  
    def printList(self):  
        current = self.head  
        print("List: ", end="")  
        while current is not None:  
            print(current.data, end=" ")  
            current = current.next  
        print()  

    #链表长度
    def length(self):
        position = self.head
        count = 0
        while position:
            count += 1
            position = position.next
        return count  
    
    #增加头部元素  
    def prepend(self, data):      
        new_node = Node(data)      
        new_node.next = self.head      
        self.head = new_node

    #增加尾部元素
    def append(self, data):  
        new_node = Node(data)  
        if self.head is None:  # 如果链表为空，则将新节点设置为头部节点  
            self.head = new_node  
        else:  
            current = self.head  
            while current.next is not None:  # 遍历链表找到最后一个节点  
                current = current.next  
            current.next = new_node  # 将最后一个节点的指针指向新节点
    
    #增加中间元素
    def insert(self, data, position):  
        if position <= 0:
            self.prepend(data)
        elif position >=self.length():
            self.append(position)
        else:
            pre = self.head
            count = 0
            while count < position - 1:
                count += 1
                pre = pre.next
            node = Node(data)
            node.next = pre.next
            pre.next = node

    #删除头部节点
    def delete_head(self):  
        if self.head is not None:  
            self.head = self.head.next  
        else:  
            print("链表为空，无法删除头部节点")  
    
    #删除中间节点
    def delete_middle(self, key):  
        if self.head is None:  
            print("链表为空，无法删除中间节点")  
            return  
        temp = self.head  
        count = 0  
        while temp is not None and count < key:  
            temp = temp.next  
            count += 1  
        if temp is None:  
            print("链表长度小于给定的中间节点位置")  
        elif temp.next is None:  
            print("给定的位置是最后一个节点，无法删除")  
        else:  
            temp.next = temp.next.next  
            return  
    
    #删除尾部节点
    def delete_end(self):  
        if self.head is None:  
            print("链表为空，无法删除尾部节点")  
            return  
        temp = self.head  
        while temp.next is not None:  
            temp = temp.next  
        temp.next = None  
        return
    
    #查找元素位置
    def find_position(self, data):  
        current = self.head  
        position = 0  
        while current is not None:  
            if current.data == data:  
                return position  
            current = current.next  
            position += 1  
        return -1  # 如果未找到，则返回-1

if __name__ == "__main__":  
    n = int(input("Enter the number of nodes: ")) #输入节点个数  
    linked_list = LinkedList()  
    linked_list.createList(n)  
    linked_list.printList()  


List: 3 5 7 2 6 


In [ ]:
# 使用同一个链表对象进行操作  
linked_list.prepend(8)  
linked_list.printList()

List: 8 3 5 7 2 6 


In [ ]:
linked_list.append(4)
linked_list.printList()

List: 8 3 5 7 2 6 4 


In [ ]:
linked_list.insert(9,3)
linked_list.printList()

List: 8 3 5 9 7 2 6 4 


In [ ]:
linked_list.delete_head()
linked_list.printList()

List: 3 5 9 7 2 6 4 


In [ ]:
linked_list.delete_end()
linked_list.printList()

List: 3 5 9 7 2 6 4 


In [ ]:
linked_list.delete_middle(1)
linked_list.printList()

List: 3 5 7 2 6 4 


In [ ]:
linked_list.find_position(5)

1

In [6]:
class Student:  
    def __init__(self, name, age, gender, student_id):  
        self.name = name  
        self.age = age  
        self.gender = gender  
        self.student_id = student_id
        self.next = None  
  
    def __str__(self):  
        return f'{self.name} ({self.gender}), {self.age}岁, 学号: {self.student_id}'  
  
  
class LinkedList:  
    def __init__(self):  
        self.head = None  
  
    def add_student(self, student):  
        if not self.head:  
            self.head = student  
        else:  
            current = self.head  
            while current.next:  
                current = current.next  
            current.next = student  
  
    def remove_student(self, name):  
        current = self.head  
        if current and current.name == name:  
            self.head = current.next  
            current = None  
            return True  
        prev = None  
        while current and current.name != name:  
            prev = current  
            current = current.next  
        if current:  
            prev.next = current.next  
            current = None  
            return True  
        return False  
  
    def update_student(self, name, age, gender):  
        current = self.head  
        while current and current.name != name:  
            current = current.next  
        if current:  
            current.age = age  
            current.gender = gender  
            return True  
        return False  
  
    def find_student(self, name):  
        current = self.head  
        while current and current.name != name:  
            current = current.next  
        if current:  
            return current  
        return None
    
    def print_student_list(student_list):  
        current = student_list.head  
        while current:  
            print(current)  
            current = current.next  

In [13]:
# 创建链表对象  
student_list = LinkedList()  
  
# 添加学生对象到链表  
student1 = Student("张三", 20, "男", "1001")  
student2 = Student("李四", 21, "女", "1002")  
student3 = Student("王五", 19, "男", "1003")  
student_list.add_student(student1)  
student_list.add_student(student2)  
student_list.add_student(student3)
student_list.print_student_list()  


张三 (男), 20岁, 学号: 1001
李四 (女), 21岁, 学号: 1002
王五 (男), 19岁, 学号: 1003


In [12]:
# 创建链表对象  
student_list = LinkedList()  
  
# 添加学生对象到链表  
student1 = Student("张三", 20, "男", "1001")  
student2 = Student("李四", 21, "女", "1002")  
student3 = Student("王五", 19, "男", "1003")  
student_list.add_student(student1)  
student_list.add_student(student2)  
student_list.add_student(student3)
student_list.print_student_list()  

print("---------------------------------------------------------------------")\

student_list.update_student("张三",19,"女",)
student_list.remove_student(student2)
student_list.print_student_list()  

张三 (男), 20岁, 学号: 1001
李四 (女), 21岁, 学号: 1002
王五 (男), 19岁, 学号: 1003
---------------------------------------------------------------------
张三 (女), 19岁, 学号: 1001
李四 (女), 21岁, 学号: 1002
王五 (男), 19岁, 学号: 1003


In [ ]:
import queue  
  
# 创建一个队列  
q = queue.Queue()  
  
print("插入元素到队尾")  
q.put(5)  
q.put(2)  
q.put(1)  
  
print("删除队头元素并返回该元素")  
item = q.get()  
print("删除的元素：" + str(item))  
print("队列中的元素：" + str(q.queue))

print("遍历队列中的元素")
while not q.empty():  
    item = q.get()  
    print(item)

print(q.queue)

插入元素到队尾
删除队头元素并返回该元素
删除的元素：5
队列中的元素：deque([2, 1])
遍历队列中的元素
2
1
deque([])


In [1]:
from collections import deque  
    
dq = deque()  
    
dq.appendleft('a')  # 在前端插入 'a'  
dq.appendleft('b')  # 在前端插入 'b'，现在队列为 ['b', 'a']  
    
print("在前端插入元素后:", list(dq))  
  
dq.append('c')  # 在后端插入 'c'  
dq.append('d')  # 在后端插入 'd'，现在队列为 ['b', 'a', 'c', 'd']  
  
print("在后端插入元素后:", list(dq))  
  
dq.popleft()  # 删除并返回前端的元素 'b'  
  
print("从前端删除元素后:", list(dq))  
   
dq.pop()  # 删除并返回后端的元素 'd'  
  
print("从后端删除元素后:", list(dq))

在前端插入元素后: ['b', 'a']
在后端插入元素后: ['b', 'a', 'c', 'd']
从前端删除元素后: ['a', 'c', 'd']
从后端删除元素后: ['a', 'c']


In [ ]:
from collections import deque  
  
# 创建一个空的双端队列  
dq = deque()

print("在队列的右侧添加元素")  
dq.append(5)  
dq.append(2)
print(dq)
  
print("在队列的左侧添加元素")  
dq.appendleft(1)
print(dq)
  
print("从队列的右侧删除元素并返回该元素")  
right_element = dq.pop()  
print(right_element) 
  
print("从队列的左侧删除元素并返回该元素")  
left_element = dq.popleft()  
print(left_element)

在队列的右侧添加元素
deque([5, 2])
在队列的左侧添加元素
deque([1, 5, 2])
从队列的右侧删除元素并返回该元素
2
从队列的左侧删除元素并返回该元素
1


In [ ]:
from queue import Queue

class WeChatUser:
    def __init__(self, name):
        self.name = name
        self.message_queue = Queue()

    def send_message(self, message, recipient):
        print(f"{self.name}发送消息给{recipient.name}：{message}")
        recipient.receive_message(message)

    def receive_message(self, message):
        print(f"{self.name}收到消息：{message}")
        self.message_queue.put(message)
        print(f"{self.name}的消息队列内容：{list(self.message_queue.queue)}")

def main():
    # 创建两个用户
    xiaomei = WeChatUser("小美")
    xiaoshuai = WeChatUser("小帅")

    # 小帅发送消息给小美
    xiaoshuai.send_message("你好，小美！", xiaomei)

    # 模拟消息队列
    while not xiaomei.message_queue.empty():
        message = xiaomei.message_queue.get()
        print(f"{xiaomei.name}收到消息：{message}")

    # 显示最终消息队列状态
    print(f"{xiaomei.name}的最终消息队列内容：{list(xiaomei.message_queue.queue)}")

if __name__ == "__main__":
    main()


小帅发送消息给小美：你好，小美！
小美收到消息：你好，小美！
小美的消息队列内容：['你好，小美！']
小美收到消息：你好，小美！
小美的最终消息队列内容：[]


In [ ]:
class CircularQueue:  
    def __init__(self, k: int):  
        self.k = k  # 循环队列的容量  
        self.queue = [None] * k  # 初始化循环队列  
        self.head = -1  # 队头指针，初始值为-1，表示队列为空  
        self.tail = -1  # 队尾指针，初始值为-1，表示队列为空  
  
    def enqueue(self, value: int) -> bool:  
        if self.is_full():  
            return False  # 队列已满，无法进队  
        if self.is_empty():  
            self.head = 0  # 如果队列为空，将队头指针指向第一个元素的位置  
        self.tail = (self.tail + 1) % self.k  # 计算新的队尾指针位置  
        self.queue[self.tail] = value  # 在队尾插入元素  
        return True  
  
    def dequeue(self) -> bool:  
        if self.is_empty():  
            return False  # 队列为空，无法出队  
        if self.head == self.tail:  # 如果队列中只有一个元素，出队后将队头和队尾指针都指向-1，表示队列为空  
            self.head = -1  
            self.tail = -1  
            return True  
        self.head = (self.head + 1) % self.k  # 计算新的队头指针位置  
        return True  
  
    def is_empty(self) -> bool:  
        return self.head == -1 and self.tail == -1  # 如果队头和队尾指针都指向-1，表示队列为空  
  
    def is_full(self) -> bool:  
        return (self.tail + 1) % self.k == self.head  # 如果队列中下一个元素的位置是队头指针的位置，表示队列已满

cq = CircularQueue(3)  # 创建一个容量为3的循环队列  
print(cq.enqueue("张三"))  # True  
print(cq.enqueue("李四"))  # True  
print(cq.enqueue("王五"))  # True
print(cq.enqueue("赵六"))  # False，队列已满，无法进队     
print(cq.dequeue())  # True，出队1  
print(cq.dequeue())  # True，出队2  
print(cq.dequeue())  # True，出队3
print(cq.dequeue())  # False，队列为空，无法出队

True
True
True
False
True
True
True
False


In [ ]:
class Stack:  
    def __init__(self):  
        self.stack = []  
    
    #入栈操作
    def push(self, item):  
        self.stack.append(item)  
    #出栈操作
    def pop(self):  
        if not self.is_empty():  
            return self.stack.pop()  
        else:  
            return None  
    
    #查看栈顶元素
    def peek(self):  
        if not self.is_empty():  
            return self.stack[-1]  
        else:  
            return None  
  
    #判断栈是否为空
    def is_empty(self):  
        return len(self.stack) == 0  

    #查看栈的尺寸
    def size(self):  
        return len(self.stack)

In [ ]:
class Browser:  
    def __init__(self):  
        self.history = []  
        self.current_page = None  
      
    def visit_page(self, page):  
        self.history.append(self.current_page)  
        self.current_page = page  
      
    def go_back(self):  
        if len(self.history) > 0:  
            self.current_page = self.history.pop()  
        else:  
            print("Can't go back anymore.")

In [ ]:
class ListNode:  
    """链表节点类"""  
    def __init__(self, value=None):  
        self.value = value  # 节点存储的值，可以是任意类型  
        self.next = None    # 指向下一个节点的指针  
  
class LinkedList:  
    """单向链表类"""  
    def __init__(self):  
        self.head = None  # 链表头节点  
  
    def append(self, value):  
        """在链表末尾添加一个新节点"""  
        if not self.head:  
            self.head = ListNode(value)  
        else:  
            current = self.head  
            while current.next:  
                current = current.next  
            current.next = ListNode(value)  
  
    def display(self):  
        """打印链表中的所有元素"""  
        current = self.head  
        while current:  
            print(current.value, end=' ')  
            current = current.next  
        print()  # 换行  
  
# 使用示例  
if __name__ == "__main__":  
    ll = LinkedList()  
    ll.append(1)  
    ll.append("Hello")  
    ll.append(3.14)  
    ll.append([1, 2, 3])  
    ll.display()  # 输出: 1 Hello 3.14 [1, 2, 3]

1 Hello 3.14 [1, 2, 3] 
